-- =====================================================================
-- Proyecto 1 BI: Tablas
-- =====================================================================

DROP TABLE IF EXISTS morosidad, comision, interes, pago, tipo_comision, rango_atraso, canal_pago, credito, agencia, producto_credito, tipo_credito, cliente, segmento, ubicacion, region CASCADE;

-- =====================================================================
-- Tabla Región
-- Regiones socioeconómicas de Costa Rica.
-- =====================================================================

CREATE TABLE region (
    id_region      SMALLINT     GENERATED BY DEFAULT AS IDENTITY,
    codigo_region  VARCHAR(10)  NOT NULL,
    nombre_region  VARCHAR(50)  NOT NULL,

    CONSTRAINT pk_region PRIMARY KEY (id_region),
    CONSTRAINT uq_region_codigo UNIQUE (codigo_region)
);

-- =====================================================================
-- Tabla Ubicación
-- Cantones donde residen los clientes y se ubican las agencias.
-- =====================================================================

CREATE TABLE ubicacion (
    id_ubicacion  INT          GENERATED BY DEFAULT AS IDENTITY,
    provincia     VARCHAR(30)  NOT NULL,
    canton        VARCHAR(50)  NOT NULL,
    id_region     SMALLINT     NOT NULL,

    CONSTRAINT pk_ubicacion PRIMARY KEY (id_ubicacion),
    CONSTRAINT uq_ubicacion_provincia_canton UNIQUE (provincia, canton),
    CONSTRAINT fk_ubicacion_region
        FOREIGN KEY (id_region) REFERENCES region (id_region),
    CONSTRAINT ck_ubicacion_provincia CHECK (provincia IN (
        'San José', 'Alajuela', 'Cartago', 'Heredia', 'Guanacaste', 'Puntarenas', 'Limón'))
);

-- =====================================================================
-- Tabla Segmento
-- Clasificación de los clientes según su fuente de ingresos.
-- =====================================================================

CREATE TABLE segmento (
    id_segmento      SMALLINT     GENERATED BY DEFAULT AS IDENTITY,
    codigo_segmento  VARCHAR(10)  NOT NULL,
    nombre_segmento  VARCHAR(50)  NOT NULL,
    descripcion      VARCHAR(200),

    CONSTRAINT pk_segmento PRIMARY KEY (id_segmento),
    CONSTRAINT uq_segmento_codigo UNIQUE (codigo_segmento)
);

-- =====================================================================
-- Tabla Cliente
-- Asociados de la cooperativa.
-- =====================================================================

CREATE TABLE cliente (
    id_cliente             INT          GENERATED BY DEFAULT AS IDENTITY,
    numero_identificacion  VARCHAR(20)  NOT NULL,
    nombre                 VARCHAR(50)  NOT NULL,
    primer_apellido        VARCHAR(50)  NOT NULL,
    segundo_apellido       VARCHAR(50),
    fecha_nacimiento       DATE         NOT NULL,
    fecha_ingreso          DATE         NOT NULL,
    id_segmento            SMALLINT     NOT NULL,
    id_ubicacion           INT          NOT NULL,
    activo                 BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uq_cliente_identificacion UNIQUE (numero_identificacion),
    CONSTRAINT fk_cliente_segmento
        FOREIGN KEY (id_segmento) REFERENCES segmento (id_segmento),
    CONSTRAINT fk_cliente_ubicacion
        FOREIGN KEY (id_ubicacion) REFERENCES ubicacion (id_ubicacion),
    CONSTRAINT ck_cliente_fechas CHECK (fecha_nacimiento < fecha_ingreso)
);

-- =====================================================================
-- Tabla Tipo de crédito
-- Clasificación general de los créditos.
-- =====================================================================

CREATE TABLE tipo_credito (
    id_tipo_credito  SMALLINT     GENERATED BY DEFAULT AS IDENTITY,
    codigo_tipo      VARCHAR(10)  NOT NULL,
    nombre_tipo      VARCHAR(50)  NOT NULL,
    tipo_garantia    VARCHAR(20)  NOT NULL,
    descripcion      VARCHAR(200),
	
    CONSTRAINT pk_tipo_credito PRIMARY KEY (id_tipo_credito),
    CONSTRAINT uq_tipo_credito_codigo UNIQUE (codigo_tipo),
    CONSTRAINT ck_tipo_credito_garantia
        CHECK (tipo_garantia IN ('FIDUCIARIA', 'HIPOTECARIA', 'PRENDARIA', 'MIXTA'))
);

-- =====================================================================
-- Tabla Producto de crédito
-- Catálogo de productos de crédito y sus condiciones de referencia.
-- =====================================================================

CREATE TABLE producto_credito (
    id_producto                 SMALLINT      GENERATED BY DEFAULT AS IDENTITY,
    codigo_producto             VARCHAR(10)   NOT NULL,
    nombre_producto             VARCHAR(80)   NOT NULL,
    id_tipo_credito             SMALLINT      NOT NULL,
    moneda                      CHAR(3)       NOT NULL DEFAULT 'CRC',
    monto_minimo                NUMERIC(15,2) NOT NULL,
    monto_maximo                NUMERIC(15,2) NOT NULL,
    plazo_minimo_meses          SMALLINT      NOT NULL,
    plazo_maximo_meses          SMALLINT      NOT NULL,
    tasa_interes_min_anual      NUMERIC(5,2)  NOT NULL,
    tasa_interes_max_anual      NUMERIC(5,2)  NOT NULL,
    tasa_moratoria_anual        NUMERIC(5,2)  NOT NULL,
    pct_comision_formalizacion  NUMERIC(5,2)  NOT NULL,
    fecha_lanzamiento           DATE          NOT NULL,
    activo                      BOOLEAN       NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_producto_credito PRIMARY KEY (id_producto),
    CONSTRAINT uq_producto_credito_codigo UNIQUE (codigo_producto),
    CONSTRAINT fk_producto_credito_tipo
        FOREIGN KEY (id_tipo_credito) REFERENCES tipo_credito (id_tipo_credito),
    CONSTRAINT ck_producto_moneda CHECK (moneda IN ('CRC', 'USD')),
    CONSTRAINT ck_producto_monto
        CHECK (monto_minimo > 0 AND monto_maximo >= monto_minimo),
    CONSTRAINT ck_producto_plazo
        CHECK (plazo_minimo_meses > 0 AND plazo_maximo_meses >= plazo_minimo_meses),
    CONSTRAINT ck_producto_tasa
        CHECK (tasa_interes_min_anual > 0 AND tasa_interes_max_anual >= tasa_interes_min_anual),
    CONSTRAINT ck_producto_recargos
        CHECK (tasa_moratoria_anual >= 0 AND pct_comision_formalizacion >= 0)
);

-- =====================================================================
-- Tabla Agencia
-- Agencias donde se formalizan los créditos.
-- =====================================================================

CREATE TABLE agencia (
    id_agencia      SMALLINT     GENERATED BY DEFAULT AS IDENTITY,
    codigo_agencia  VARCHAR(10)  NOT NULL,
    nombre_agencia  VARCHAR(80)  NOT NULL,
    id_ubicacion    INT          NOT NULL,
    fecha_apertura  DATE         NOT NULL,
    activa          BOOLEAN      NOT NULL DEFAULT TRUE,
	
    CONSTRAINT pk_agencia PRIMARY KEY (id_agencia),
    CONSTRAINT uq_agencia_codigo UNIQUE (codigo_agencia),
    CONSTRAINT fk_agencia_ubicacion
        FOREIGN KEY (id_ubicacion) REFERENCES ubicacion (id_ubicacion)
);

-- =====================================================================
-- Tabla Credito
-- Una fila por operación de crédito formalizada.
-- =====================================================================

CREATE TABLE credito (
    id_credito          INT           GENERATED BY DEFAULT AS IDENTITY,
    numero_operacion    VARCHAR(20)   NOT NULL,
    id_cliente          INT           NOT NULL,
    id_producto         SMALLINT      NOT NULL,
    id_agencia          SMALLINT      NOT NULL,
    fecha_solicitud     DATE          NOT NULL,
    fecha_aprobacion    DATE          NOT NULL,
    fecha_desembolso    DATE          NOT NULL, 
    fecha_primer_pago   DATE          NOT NULL,
    fecha_vencimiento   DATE          NOT NULL,
    monto_solicitado    NUMERIC(15,2) NOT NULL,
    monto_aprobado      NUMERIC(15,2) NOT NULL,
    plazo_meses         SMALLINT      NOT NULL,
    tasa_interes_anual  NUMERIC(5,2)  NOT NULL,
    cuota_mensual       NUMERIC(15,2) NOT NULL,
    estado_credito      VARCHAR(15)   NOT NULL DEFAULT 'VIGENTE',

    CONSTRAINT pk_credito PRIMARY KEY (id_credito),
    CONSTRAINT uq_credito_numero_operacion UNIQUE (numero_operacion),
    CONSTRAINT fk_credito_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
    CONSTRAINT fk_credito_producto
        FOREIGN KEY (id_producto) REFERENCES producto_credito (id_producto),
    CONSTRAINT fk_credito_agencia
        FOREIGN KEY (id_agencia) REFERENCES agencia (id_agencia),
    CONSTRAINT ck_credito_montos
        CHECK (monto_aprobado > 0 AND monto_solicitado >= monto_aprobado),
    CONSTRAINT ck_credito_condiciones
        CHECK (plazo_meses > 0 AND tasa_interes_anual > 0 AND cuota_mensual > 0),
    CONSTRAINT ck_credito_fechas CHECK (
        fecha_solicitud   <= fecha_aprobacion
        AND fecha_aprobacion  <= fecha_desembolso
        AND fecha_desembolso  <  fecha_primer_pago
        AND fecha_primer_pago <= fecha_vencimiento),
    CONSTRAINT ck_credito_estado CHECK (
        estado_credito IN ('VIGENTE', 'CANCELADO', 'COBRO_JUDICIAL', 'CASTIGADO'))
);

-- =====================================================================
-- Tabla Canal de pago
-- Medios por los que los clientes pagan sus créditos.
-- =====================================================================

CREATE TABLE canal_pago (
    id_canal      SMALLINT     GENERATED BY DEFAULT AS IDENTITY,
    codigo_canal  VARCHAR(10)  NOT NULL,
    nombre_canal  VARCHAR(50)  NOT NULL,
    es_digital    BOOLEAN      NOT NULL,

    CONSTRAINT pk_canal_pago PRIMARY KEY (id_canal),
    CONSTRAINT uq_canal_pago_codigo UNIQUE (codigo_canal)
);

-- =====================================================================
-- Tabla Rango de atraso
-- Clasificación de los créditos según sus días de atraso.
-- =====================================================================

CREATE TABLE rango_atraso (
    id_rango      SMALLINT     GENERATED BY DEFAULT AS IDENTITY,
    codigo_rango  VARCHAR(10)  NOT NULL,
    nombre_rango  VARCHAR(50)  NOT NULL,
    dias_minimo   SMALLINT     NOT NULL,
    dias_maximo   SMALLINT,

    CONSTRAINT pk_rango_atraso PRIMARY KEY (id_rango),
    CONSTRAINT uq_rango_atraso_codigo UNIQUE (codigo_rango),
    CONSTRAINT ck_rango_atraso_dias
        CHECK (dias_minimo >= 0 AND (dias_maximo IS NULL OR dias_maximo >= dias_minimo))
);

-- =====================================================================
-- Tabla Tipo de comisión
-- Conceptos por los que la cooperativa cobra comisiones.
-- =====================================================================

CREATE TABLE tipo_comision (
    id_tipo_comision  SMALLINT     GENERATED BY DEFAULT AS IDENTITY,
    codigo_comision   VARCHAR(10)  NOT NULL,
    nombre_comision   VARCHAR(50)  NOT NULL,
    descripcion       VARCHAR(200),

    CONSTRAINT pk_tipo_comision PRIMARY KEY (id_tipo_comision),
    CONSTRAINT uq_tipo_comision_codigo UNIQUE (codigo_comision)
);

-- =====================================================================
-- Tabla Pago
-- Una fila por cuota pagada de un crédito.
-- =====================================================================

CREATE TABLE pago (
    id_pago                  INT           GENERATED BY DEFAULT AS IDENTITY,
    id_credito               INT           NOT NULL,
    id_canal                 SMALLINT      NOT NULL,
    numero_cuota             SMALLINT      NOT NULL,
    fecha_vencimiento_cuota  DATE          NOT NULL,
    fecha_pago               DATE          NOT NULL,
    dias_atraso              SMALLINT      NOT NULL DEFAULT 0,
    monto_principal          NUMERIC(15,2) NOT NULL,
    monto_interes            NUMERIC(15,2) NOT NULL,
    monto_interes_moratorio  NUMERIC(15,2) NOT NULL DEFAULT 0,
    monto_total              NUMERIC(15,2) NOT NULL,

    CONSTRAINT pk_pago PRIMARY KEY (id_pago),
    CONSTRAINT uq_pago_credito_cuota UNIQUE (id_credito, numero_cuota),
    CONSTRAINT fk_pago_credito
        FOREIGN KEY (id_credito) REFERENCES credito (id_credito),
    CONSTRAINT fk_pago_canal
        FOREIGN KEY (id_canal) REFERENCES canal_pago (id_canal),
    CONSTRAINT ck_pago_cuota CHECK (numero_cuota > 0),
    CONSTRAINT ck_pago_atraso CHECK (dias_atraso >= 0),
    CONSTRAINT ck_pago_montos CHECK (
        monto_principal >= 0 AND monto_interes >= 0 AND monto_interes_moratorio >= 0
        AND monto_total = monto_principal + monto_interes + monto_interes_moratorio)
);

-- =====================================================================
-- Tabla Interés
-- Intereses ordinarios devengados por cuota y moratorios cobrados.
-- =====================================================================

CREATE TABLE interes (
    id_interes     INT           GENERATED BY DEFAULT AS IDENTITY,
    id_credito     INT           NOT NULL,
    numero_cuota   SMALLINT      NOT NULL,
    tipo_interes   VARCHAR(10)   NOT NULL,
    fecha_devengo  DATE          NOT NULL,
    monto_interes  NUMERIC(15,2) NOT NULL,

    CONSTRAINT pk_interes PRIMARY KEY (id_interes),
    CONSTRAINT uq_interes_credito_cuota_tipo UNIQUE (id_credito, numero_cuota, tipo_interes),
    CONSTRAINT fk_interes_credito
        FOREIGN KEY (id_credito) REFERENCES credito (id_credito),
    CONSTRAINT ck_interes_tipo CHECK (tipo_interes IN ('ORDINARIO', 'MORATORIO')),
    CONSTRAINT ck_interes_monto CHECK (monto_interes >= 0)
);

-- =====================================================================
-- Tabla Comisión
-- Comisiones cobradas sobre los créditos.
-- =====================================================================

CREATE TABLE comision (
    id_comision       INT           GENERATED BY DEFAULT AS IDENTITY,
    id_credito        INT           NOT NULL,
    id_tipo_comision  SMALLINT      NOT NULL,
    fecha_cobro       DATE          NOT NULL,
    monto_comision    NUMERIC(15,2) NOT NULL,

    CONSTRAINT pk_comision PRIMARY KEY (id_comision),
    CONSTRAINT fk_comision_credito
        FOREIGN KEY (id_credito) REFERENCES credito (id_credito),
    CONSTRAINT fk_comision_tipo
        FOREIGN KEY (id_tipo_comision) REFERENCES tipo_comision (id_tipo_comision),
    CONSTRAINT ck_comision_monto CHECK (monto_comision > 0)
);

-- =====================================================================
-- Tabla Morosidad
-- Situación de cada crédito al cierre de cada mes.
-- =====================================================================

CREATE TABLE morosidad (
    id_morosidad      INT           GENERATED BY DEFAULT AS IDENTITY,
    id_credito        INT           NOT NULL,
    fecha_corte       DATE          NOT NULL,
    saldo_pendiente   NUMERIC(15,2) NOT NULL,
    cuotas_atrasadas  SMALLINT      NOT NULL DEFAULT 0,
    monto_atrasado    NUMERIC(15,2) NOT NULL DEFAULT 0,
    dias_atraso       SMALLINT      NOT NULL DEFAULT 0,
    id_rango          SMALLINT      NOT NULL,

    CONSTRAINT pk_morosidad PRIMARY KEY (id_morosidad),
    CONSTRAINT uq_morosidad_credito_corte UNIQUE (id_credito, fecha_corte),
    CONSTRAINT fk_morosidad_credito
        FOREIGN KEY (id_credito) REFERENCES credito (id_credito),
    CONSTRAINT fk_morosidad_rango
        FOREIGN KEY (id_rango) REFERENCES rango_atraso (id_rango),
    CONSTRAINT ck_morosidad_valores CHECK (
        saldo_pendiente >= 0 AND cuotas_atrasadas >= 0
        AND monto_atrasado >= 0 AND dias_atraso >= 0)
);

-- =====================================================================
-- Índices para acelerar las consultas
-- =====================================================================

CREATE INDEX ix_ubicacion_region ON ubicacion (id_region);
CREATE INDEX ix_cliente_segmento  ON cliente (id_segmento);
CREATE INDEX ix_cliente_ubicacion ON cliente (id_ubicacion);
CREATE INDEX ix_producto_credito_tipo ON producto_credito (id_tipo_credito);
CREATE INDEX ix_agencia_ubicacion ON agencia (id_ubicacion);
CREATE INDEX ix_credito_cliente    ON credito (id_cliente);
CREATE INDEX ix_credito_producto   ON credito (id_producto);
CREATE INDEX ix_credito_agencia    ON credito (id_agencia);
CREATE INDEX ix_credito_desembolso ON credito (fecha_desembolso);
CREATE INDEX ix_pago_credito ON pago (id_credito);
CREATE INDEX ix_pago_canal   ON pago (id_canal);
CREATE INDEX ix_pago_fecha   ON pago (fecha_pago);
CREATE INDEX ix_interes_credito ON interes (id_credito);
CREATE INDEX ix_interes_fecha   ON interes (fecha_devengo);
CREATE INDEX ix_comision_credito ON comision (id_credito);
CREATE INDEX ix_comision_tipo    ON comision (id_tipo_comision);
CREATE INDEX ix_comision_fecha   ON comision (fecha_cobro);
CREATE INDEX ix_morosidad_credito ON morosidad (id_credito);
CREATE INDEX ix_morosidad_corte   ON morosidad (fecha_corte);
CREATE INDEX ix_morosidad_rango   ON morosidad (id_rango);
